require: rubocop-rspec

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/**/*.erb_spec.rb'

RSpec/FilePath:
  Exclude:
    - 'spec/**/*_routing_spec.rb'